[package]
name = "nixb-store"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
embed = ["nixb-cpp/embed"]
nix-2-35 = ["nixb-cpp/nix-2-35", "nixb-sys/nix-2-35"]

[dependencies]
nixb-c-context = { workspace = true }
nixb-cpp = { workspace = true, features = ["store"] }
nixb-error = { workspace = true }
nixb-sys = { workspace = true }

[build-dependencies]
pkg-config = { workspace = true }

[lints]
workspace = true
