[package]
name = "nixb"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["nix-2-35"]

compact_str = ["nixb-expr?/compact_str"]
either = ["nixb-expr?/either"]
embed = [
  "nixb-expr?/embed",
  "nixb-store?/embed",
]
expr = ["nixb-expr"]
fetchers = ["nixb-fetchers"]
nix-2-35 = [
  "nixb-expr?/nix-2-35",
  "nixb-fetchers?/nix-2-35",
  "nixb-plugin?/nix-2-35",
  "nixb-store?/nix-2-35",
]
plugin = ["nixb-plugin"]
smallvec = ["nixb-expr?/smallvec"]
std = ["nixb-expr?/std"]
store = ["nixb-store"]

[dependencies]
nixb-c-context = { workspace = true }
nixb-error = { workspace = true }

nixb-expr = { workspace = true, optional = true }
nixb-fetchers = { workspace = true, optional = true }
nixb-plugin = { workspace = true, optional = true }
nixb-store = { workspace = true, optional = true }

[lints]
workspace = true
