[package]
name = "nixb-examples"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["nix-2-35"]
embed = ["nixb/embed"]
nix-2-35 = ["nixb/nix-2-35"]
plugin = ["nixb/plugin"]

[dependencies]
nixb = { workspace = true, features = ["expr"] }

[[example]]
name = "embedded"
path = "embedded.rs"
required-features = ["embed"]

[[example]]
name = "hello_world"
path = "hello_world.rs"
crate-type = ["cdylib"]
required-features = ["plugin"]

[[example]]
name = "readme"
path = "readme.rs"
crate-type = ["cdylib"]
required-features = ["plugin"]

[lints.rust]
refining-impl-trait.level = "allow"
