name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Configure Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run formatting check
        run: nix run .#check-formatting

  examples:
    name: Run examples (Nix ${{ matrix.nix-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nix-version:
          - 2.32
          - 2.33
          - 2.34
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run example checks
        run: |
          nix_feature=${{ matrix.nix-version }}
          nix run .#check-examples.nix-${nix_feature//./-}
